spring:
  application:
    name: cube-ms-order
  docker:
    compose:
      enabled: true

  cloud:
    openfeign:
      client:
        config:
          asaas:
            url: https://api-sandbox.asaas.com
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: ${DB_USERNAME:cubeMsOrder}
    password: ${DB_PASSWORD:cubeMsOrder}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082
  error:
    include-message: always

  asaas:
    api-key: "${ASAAS_API_KEY}"
